version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./rtmp:/etc/rtmp
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"

  nginx:
    image: alfg/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./rtmp:/etc/rtmp
